name: 'Duplicate Check'
description: "Duplicate data check for the program-list."
runs:
  using: 'composite'
  steps:
    - run: sudo apt-get install python3-setuptools
      shell: bash
    - run: pip3 install tldextract
      shell: bash
    - run: python3 ${{ github.action_path }}/duplicate_check.py ${{ github.action_path }}/../../../
      shell: bash
